"use client";

import Can from "@/components/authorization/Can";
import ConfirmDeleteModal from "@/components/common/ConfirmDeleteModal";
import Input from "@/components/form/input/InputField";
import SortableTableHeader from "@/components/tables/SortableTableHeader";
import TablePagination from "@/components/tables/TablePagination";
import Badge from "@/components/ui/badge/Badge";
import ButtonLink from "@/components/ui/button/ButtonLink";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/components/ui/table";
import { useAuthorization } from "@/hooks/useAuthorization";
import { useListParams } from "@/hooks/useListParams";
import { PencilIcon, PlusIcon, TrashBinIcon } from "@/icons";
import { toErrorMessage } from "@/lib/api/types";
import { PERMISSIONS } from "@/lib/authz";
import { settingCategoriesService, settingsService } from "@/lib/settings/service";
import type { Setting, SettingCategory, SortOrder } from "@/lib/settings/types";
import { formatDateTime } from "@/lib/utils/date";
import { DEFAULT_PAGE_SIZE, SEARCH_DEBOUNCE_MS, parsePositiveInt } from "@/lib/utils/table";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

const SORT_FIELDS = ["key", "type", "createdAt", "updatedAt"] as const;
type SortField = (typeof SORT_FIELDS)[number];
const NOTICES: Record<string, string> = { created: "Setting created successfully.", updated: "Setting updated successfully." };

export default function SettingsTable() {
  const { searchParams, updateParams, resetParams } = useListParams(); const { can } = useAuthorization();
  const page = parsePositiveInt(searchParams.get("page"), 1); const limit = parsePositiveInt(searchParams.get("limit"), DEFAULT_PAGE_SIZE); const search = searchParams.get("search") ?? ""; const sortBy = (SORT_FIELDS.includes(searchParams.get("sortBy") as SortField) ? searchParams.get("sortBy") : "key") as SortField; const sortOrder: SortOrder = searchParams.get("sortOrder") === "DESC" ? "DESC" : "ASC";
  const [settings, setSettings] = useState<Setting[]>([]); const [categories, setCategories] = useState<SettingCategory[]>([]); const [isLoading, setIsLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [refreshToken, setRefreshToken] = useState(0); const [searchDraft, setSearchDraft] = useState(search); const [flash, setFlash] = useState(""); const [pendingDelete, setPendingDelete] = useState<Setting | null>(null); const [isDeleting, setIsDeleting] = useState(false); const [deleteError, setDeleteError] = useState("");
  useEffect(() => { let ignore = false; setIsLoading(true); Promise.all([settingsService.list(), settingCategoriesService.list().catch(() => [])]).then(([items, categoryItems]) => { if (!ignore) { setSettings(items); setCategories(categoryItems); setLoadError(""); } }).catch((error: unknown) => { if (!ignore) { setSettings([]); setLoadError(toErrorMessage(error, "Unable to load settings.")); } }).finally(() => { if (!ignore) setIsLoading(false); }); return () => { ignore = true; }; }, [refreshToken]);
  useEffect(() => { setSearchDraft(search); }, [search]); useEffect(() => { if (searchDraft === search) return; const timer = setTimeout(() => updateParams({ search: searchDraft }, { resetPage: true }), SEARCH_DEBOUNCE_MS); return () => clearTimeout(timer); }, [search, searchDraft, updateParams]); useEffect(() => { const notice = searchParams.get("notice"); if (notice) { setFlash(NOTICES[notice] ?? ""); updateParams({}); } }, [searchParams, updateParams]);
  const categoryNames = useMemo(() => new Map(categories.map((category) => [category.id, category.name])), [categories]);
  const filtered = useMemo(() => settings.filter((item) => `${item.key} ${item.description ?? ""} ${categoryNames.get(item.categoryId) ?? ""}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => { const left = String(a[sortBy]); const right = String(b[sortBy]); const result = left.localeCompare(right, undefined, { numeric: true }); return sortOrder === "ASC" ? result : -result; }), [categoryNames, search, settings, sortBy, sortOrder]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / limit)); const currentPage = Math.min(page, totalPages); const visible = filtered.slice((currentPage - 1) * limit, currentPage * limit); useEffect(() => { if (page > totalPages && filtered.length > 0) updateParams({ page: totalPages }); }, [filtered.length, page, totalPages, updateParams]);
  const handleSort = (field: SortField) => updateParams({ sortBy: field, sortOrder: sortBy === field && sortOrder === "ASC" ? "DESC" : "ASC" }, { resetPage: true });
  const handleDelete = async () => { if (!pendingDelete) return; setIsDeleting(true); setDeleteError(""); try { await settingsService.remove(pendingDelete.id); setFlash(`Setting "${pendingDelete.key}" was deleted.`); setPendingDelete(null); setRefreshToken((token) => token + 1); } catch (error) { setDeleteError(toErrorMessage(error, "Unable to delete this setting.")); } finally { setIsDeleting(false); } };
  const hasFilters = Boolean(search) || sortBy !== "key" || sortOrder !== "ASC" || limit !== DEFAULT_PAGE_SIZE;
  return <div className="rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]">
    <div className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-base font-medium text-gray-800 dark:text-white/90">All settings</h3><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{isLoading ? "Loading settings..." : `${filtered.length} ${filtered.length === 1 ? "setting" : "settings"} found`}</p></div><Can permission={PERMISSIONS.SETTINGS.CREATE}><ButtonLink href="/settings/create" size="sm" startIcon={<PlusIcon />}>Add setting</ButtonLink></Can></div>
    <div className="flex flex-col gap-3 border-t border-gray-100 px-5 py-4 dark:border-gray-800 lg:flex-row lg:items-center"><div className="lg:max-w-xs lg:flex-1"><Input type="search" placeholder="Search settings..." value={searchDraft} onChange={(event) => setSearchDraft(event.target.value)} aria-label="Search settings" /></div>{hasFilters && <button type="button" onClick={() => { setSearchDraft(""); resetParams(); }} className="h-11 shrink-0 rounded-lg px-3 text-sm font-medium text-brand-500 transition hover:bg-brand-50 dark:hover:bg-brand-500/10">Reset</button>}</div>
    {flash && <div className="mx-5 mb-4 rounded-lg bg-success-50 p-3 text-sm text-success-600 dark:bg-success-500/15 dark:text-success-500"><p role="status">{flash}</p></div>}{loadError && <div className="mx-5 mb-4 rounded-lg bg-error-50 p-3 text-sm text-error-600 dark:bg-error-500/15 dark:text-error-400"><p role="alert">{loadError}</p></div>}
    <div className="overflow-x-auto border-t border-gray-100 dark:border-gray-800"><Table><TableHeader className="border-b border-gray-100 dark:border-gray-800"><TableRow><SortableTableHeader label="Key" field="key" sortBy={sortBy} sortOrder={sortOrder} onSort={handleSort} /><TableCell isHeader className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Value</TableCell><SortableTableHeader label="Type" field="type" sortBy={sortBy} sortOrder={sortOrder} onSort={handleSort} /><TableCell isHeader className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Category</TableCell><TableCell isHeader className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Public</TableCell><TableCell isHeader className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Editable</TableCell><SortableTableHeader label="Created" field="createdAt" sortBy={sortBy} sortOrder={sortOrder} onSort={handleSort} /><SortableTableHeader label="Updated" field="updatedAt" sortBy={sortBy} sortOrder={sortOrder} onSort={handleSort} /><TableCell isHeader className="px-5 py-3 text-right text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">Actions</TableCell></TableRow></TableHeader><TableBody>
      {isLoading && Array.from({ length: 5 }).map((_, row) => <TableRow key={row}>{Array.from({ length: 9 }).map((__, cell) => <TableCell key={cell} className="px-5 py-4"><div className="h-4 w-full animate-pulse rounded bg-gray-100 dark:bg-gray-800" /></TableCell>)}</TableRow>)}
      {!isLoading && !visible.length && !loadError && <TableRow><TableCell colSpan={9} className="px-5 py-12 text-center text-sm text-gray-500 dark:text-gray-400">{hasFilters ? "No settings match your search." : "Create your first setting to get started."}</TableCell></TableRow>}
      {visible.map((setting) => <TableRow key={setting.id} className="border-b border-gray-100 last:border-b-0 dark:border-gray-800"><TableCell className="px-5 py-4"><span className="font-medium text-gray-800 dark:text-white/90">{setting.key}</span><span className="block text-xs text-gray-500 dark:text-gray-400">{setting.description ?? "No description"}</span></TableCell><TableCell className="max-w-48 truncate px-5 py-4 text-sm text-gray-500 dark:text-gray-400"><span title={JSON.stringify(setting.value)}>{typeof setting.value === "string" ? setting.value : JSON.stringify(setting.value)}</span></TableCell><TableCell className="px-5 py-4"><Badge variant="light" color="light" size="sm">{setting.type}</Badge></TableCell><TableCell className="px-5 py-4 text-sm text-gray-500 dark:text-gray-400">{categoryNames.get(setting.categoryId) ?? "Unknown"}</TableCell><TableCell className="px-5 py-4"><Badge variant="light" color={setting.isPublic ? "success" : "light"} size="sm">{setting.isPublic ? "Yes" : "No"}</Badge></TableCell><TableCell className="px-5 py-4"><Badge variant="light" color={setting.isEditable ? "success" : "warning"} size="sm">{setting.isEditable ? "Yes" : "No"}</Badge></TableCell><TableCell className="whitespace-nowrap px-5 py-4 text-sm text-gray-500 dark:text-gray-400">{formatDateTime(setting.createdAt)}</TableCell><TableCell className="whitespace-nowrap px-5 py-4 text-sm text-gray-500 dark:text-gray-400">{formatDateTime(setting.updatedAt)}</TableCell><TableCell className="px-5 py-4"><div className="flex justify-end gap-2">{can(PERMISSIONS.SETTINGS.UPDATE) && <Link href={`/settings/${setting.id}/edit`} aria-label={`Edit ${setting.key}`} className="flex h-9 w-9 items-center justify-center rounded-lg border border-gray-300 text-gray-500 dark:border-gray-700 dark:text-gray-400"><PencilIcon /></Link>}{can(PERMISSIONS.SETTINGS.DELETE) && <button type="button" onClick={() => { setDeleteError(""); setPendingDelete(setting); }} aria-label={`Delete ${setting.key}`} className="flex h-9 w-9 items-center justify-center rounded-lg border border-gray-300 text-gray-500 hover:text-error-500 dark:border-gray-700 dark:text-gray-400"><TrashBinIcon /></button>}</div></TableCell></TableRow>)}
    </TableBody></Table></div>
    {!isLoading && filtered.length > 0 && <TablePagination page={currentPage} limit={limit} total={filtered.length} totalPages={totalPages} onPageChange={(nextPage) => updateParams({ page: nextPage })} />}
    <ConfirmDeleteModal isOpen={pendingDelete !== null} title="Delete setting" description={<>This permanently removes <span className="font-medium text-gray-700 dark:text-gray-300">{pendingDelete?.key}</span>.</>} confirmLabel="Delete setting" isDeleting={isDeleting} error={deleteError} onClose={() => { if (!isDeleting) setPendingDelete(null); }} onConfirm={handleDelete} />
  </div>;
}
